# Generated by Django 2.0 on 2018-02-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fiveGClients', models.IntegerField()),
                ('twoGClients', models.IntegerField()),
                ('channelUtilization', models.IntegerField()),
                ('poorCoverageClients', models.IntegerField()),
                ('txPowerOutput', models.IntegerField()),
                ('txFragmentCount', models.IntegerField()),
                ('rxFragmentCount', models.IntegerField()),
                ('retryCount', models.IntegerField()),
                ('multipleRetryCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='apmetrics',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_ui.Collection'),
        ),
    ]
