# Generated by Django 2.0 on 2018-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionInterval', models.IntegerField()),
            ],
        ),
    ]
